export const API = {
  BASE_URL: 'https://api.scaleupapp.club/api/',
  SIGNIN: 'auth/login',
  REGISTER: 'auth/register',
  PROFILE: 'users/profile',
  ALL_CONTENT: 'content/all-content',
  EDUCATION_DETAIL: 'users/education',
  WORK_EXPERIENCE: 'users/work-experience',
  USER_PROFILE: 'users/profiles',
  HOMEPAGE: 'content/homepage',
  FOLLOW_UNFOLLOW: 'content/followUnfollowList',
  SEARCH_USER: 'content/search-users',
  ADD_COMMENT: 'content/add-comment',

  CONTENT_CREATE: 'content/create',
  LIKE_REQUEST: 'content/like',
  UNLIKE_REQUEST: 'content/unlike',
  CONTENT_DETAIL: 'content/detail',
  FOLLOW_USER: 'content/follow',
  UNFOLLOW: 'content/unfollow',
  USER_BLOCK: 'users/block',
  USER_UNBLOCK: 'users/unblock',
  BLOCK_USER_LIST: 'users/blocked-users',
  CONTENT_VERIFY: 'content/verify',
  CHANGE_PASSWORD: 'users/change-password',
  AUTH_OTP: 'auth/otp-gen',
  OTP_VERIFY: 'auth/otp-verify',
  OTP_PASSWORD: 'auth/password-gen',
  AUTH_RESET: 'auth/reset-password',
  MARK_READ: 'content/notifications/mark-as-read',
  COMMENT_PRIVILEGE: 'users/updateCommentPrivileges',
  DELETE_ACCOUNT: 'auth/delete-account',
  USER_COURSES: 'users/courses',
  USER_CERTIFICATION: 'users/certifications',
  VERIFICATION: 'content/pending-verification',
  DELETE_CONTENT: 'content/delete',
  INCREMENT_VIEW_COUNT: 'content/view',
  POST_FEEDBACK: 'users/submitfeedback',
  GET_FEEDBACK: 'users/feedback/status',
  DELETE_COMMENT: 'content/comments',
  PREFERENCES: 'users/preferences',
  EDUCATION:'users/education',
  EXPERIENCE:'users/work-experience',
  CERTIFICATION:'users/certification',
  PROJECTS:'users/project',
  PROFILE_DETAIL:'users/profile',
  LIKEPOST:'content/like',
  UNLIKEPOST:'content/unlike',
  SAVE:"content/save",
  UNSAVE:"content/unsave",
  NOTIFICATION:"content/notifications"

};
