export const API = {
  BASE_URL1: 'http://localhost:3000/api/',
  BASE_URL: 'https://api.scaleupapp.club/api/',
  SIGNIN: 'auth/login',
  REGISTER: 'auth/register',
  APPLY_REFERRAL_CODE: 'auth/applyReferralCode',
  GET_REFERRAL_CODE: 'auth/referral',
  PROFILE: 'users/profile',
  ALL_CONTENT: 'content/all-content',
  ALL_VIDEOS: 'content/allcontent',
  EDUCATION_DETAIL: 'users/education',
  WORK_EXPERIENCE: 'users/work-experience',
  USER_PROFILE: 'users/profiles',
  HOMEPAGE: 'content/homepage',
  RECOMMEND: 'content/recommendations',
  FOLLOWERS_LIST: 'content/all-follower',
  SEARCH_USER: 'content/search-users',
  ADD_COMMENT: 'content/add-comment',
  GET_COMMENT: 'content/comment',
  CONTENT_CREATE: 'content/create',
  LIKE_REQUEST: 'content/like',
  UNLIKE_REQUEST: 'content/unlike',
  CONTENT_DETAIL: 'content/detail',
  FOLLOW_USER: 'content/follow',
  UNFOLLOW: 'content/unfollow',
  USER_BLOCK: 'users/block',
  USER_UNBLOCK: 'users/unblock',
  BLOCK_USER_LIST: 'users/blocked-users',
  CONTENT_VERIFY: 'content/verify',
  CHANGE_PASSWORD: 'users/change-password',
  AUTH_OTP: 'auth/otp-gen',
  OTP_VERIFY: 'auth/otp-verify',
  OTP_PASSWORD: 'auth/password-gen',
  AUTH_RESET: 'auth/reset-password',
  MARK_READ: 'content/notifications/mark-as-read',
  COMMENT_PRIVILEGE: 'users/updateCommentPrivileges',
  DELETE_ACCOUNT: 'auth/delete-account',
  USER_COURSES: 'users/courses',
  USER_CERTIFICATION: 'users/certifications',
  VERIFICATION: 'content/pending-verification',
  DELETE_CONTENT: 'content/delete',
  INCREMENT_VIEW_COUNT: 'content/view',
  POST_FEEDBACK: 'users/submitfeedback',
  GET_FEEDBACK: 'users/feedback/status',
  COMMENT: 'content/comments',
  PREFERENCES: 'users/preferences',
  EDUCATION: 'users/education',
  EXPERIENCE: 'users/work-experience',
  CERTIFICATION: 'users/certification',
  PROJECTS: 'users/project',
  PROFILE_DETAIL: 'users/profile',
  PROFILE_CONTENT: 'content/detail',
  LIKEPOST: 'content/like',
  UNLIKEPOST: 'content/unlike',
  SAVE: 'content/save',
  UNSAVE: 'content/unsave',
  SAVED_POSTS: 'content/saved-content',
  NOTIFICATION: 'content/notifications',
  INNERCIRCLE: 'users/inner-circle/sent-requests',
  ACCEPTREQ: 'users/inner-circle/handle-request',
  WIDRAW: 'users/inner-circle/withdraw',
  REMOVEREQ: 'users/inner-circle/remove',
  GETINNERCIRCLE: 'users/inner-circle-users',
  SENDINNERREQUEST: 'users/inner-circle/request',
  REPORTPOST: 'content/report',
  SAVE_FCM: 'users/saveFcmToken',
  USERANALYTICS: 'users/user-analytics',
  CONVERSATION: 'conversation/fetch-all',
  CREATECONVERSATION: 'conversation/create',
  SENDMESSAGE: 'chat/send',
  CHAT: 'chat',
  CREATE_GROUP: 'chat/create',
  SEND_GROUP_MSG: 'chat/group/send',
  RAPIDFIRE_CREATE: 'rapidfire-quiz/create',
  RAPIDFIRE_EDIT: 'rapidfire-quiz/edit',
  RAPIDFIRE_LIST: 'rapidfire-quiz/list',
  RAPIDFIRE_SEARCH: 'rapidfire-quiz/search',
  RAPIDFIRE_RECOMMEND: 'rapidfire-quiz/recommend',
  USER_QUIZ_ATTEMPTS: 'rapidfire-quiz/user-attempts', // New endpoint for fetching user quiz attempts
  FOLLOWING_LIST:'content/all-following',
  INNERCIRCLERECIVED:'users/inner-circle/received-requests',
  USER_PAYMENT_DETAILS_CHECK: 'users/payment-details-check',
  SAVE_UPI_DETAILS: 'users/save-upi-details',
  SAVE_BANK_DETAILS: 'users/save-bank-details',
  MIXPANEL:'ec35d7fc43e04586bbf6da1bf00dac9d',


    // USER QUIZ ENDPOINTS
    USER_QUIZ_CREATE: 'user-quiz/create',
    USER_QUIZ_UPDATE_DRAFT: 'user-quiz/:id/draft',
    USER_QUIZ_SUBMIT: 'user-quiz/:id/submit',
    USER_QUIZ_DRAFTS: 'user-quiz/drafts',
    USER_QUIZ_DELETE_DRAFT: 'user-quiz/draft/:id',
    USER_QUIZ_PUBLIC: 'user-quiz/public',
    USER_QUIZ_SEARCH: 'user-quiz/search',
    USER_QUIZ_BY_SHARE_ID: 'user-quiz/shared/:shareId',
    USER_QUIZ_BY_ID: 'user-quiz/:id',
    USER_QUIZ_DELETE: 'user-quiz/:id',
    
    // AI QUESTION GENERATION
    USER_QUIZ_AI_GENERATE: 'user-quiz/ai/generate',
    USER_QUIZ_AI_PRICE: 'user-quiz/ai/price',
    USER_QUIZ_AI_USAGE: 'user-quiz/ai/usage',
    USER_QUIZ_AI_TRANSACTIONS: 'user-quiz/ai/transactions',
    USER_QUIZ_AI_PAYMENT_INIT: 'user-quiz/ai/payment/initiate',
    USER_QUIZ_AI_PAYMENT_VERIFY: 'user-quiz/ai/payment/verify',
    USER_QUIZ_AI_WEBHOOK: 'user-quiz/ai/payment/webhook',
    USER_QUIZ_AI_REFUND: 'user-quiz/ai/refund/:transactionId',
    
    // CREATOR DASHBOARD
    USER_QUIZ_DASHBOARD: 'user-quiz/dashboard',
    USER_QUIZ_STATS: 'user-quiz/stats',
    USER_QUIZ_MY_QUIZZES: 'user-quiz/my-quizzes',
    USER_QUIZ_ANALYTICS: 'user-quiz/analytics/:id',
    USER_QUIZ_PARTICIPANTS: 'user-quiz/participants/:id',
    USER_QUIZ_BADGES: 'user-quiz/badges',
    USER_QUIZ_EARNINGS: 'user-quiz/earnings',
    USER_QUIZ_CREATOR_LEADERBOARD: 'user-quiz/creator-leaderboard',
    
    // ACCESS CONTROL
    USER_QUIZ_ACCESS_REQUEST: 'user-quiz/access/:quizId',
    USER_QUIZ_ACCESS_MY_REQUESTS: 'user-quiz/access/my-requests',
    USER_QUIZ_ACCESS_QUIZ_REQUESTS: 'user-quiz/access/quiz/:quizId',
    USER_QUIZ_ACCESS_APPROVE: 'user-quiz/access/approve/:id',
    USER_QUIZ_ACCESS_REJECT: 'user-quiz/access/reject/:id',
    USER_QUIZ_ACCESS_BULK_APPROVE: 'user-quiz/access/bulk-approve',
    USER_QUIZ_ACCESS_BULK_REJECT: 'user-quiz/access/bulk-reject',
    
    // SHARING
    USER_QUIZ_SHARE_QR: 'user-quiz/share/qr/:id',
    USER_QUIZ_SHARE_TRACK: 'user-quiz/share/track/:id',
    USER_QUIZ_SHARE_STATS: 'user-quiz/share/stats/:id',
    USER_QUIZ_SHARE_ANALYTICS: 'user-quiz/share/analytics',
    
    // ADMIN REVIEW
    USER_QUIZ_REVIEW_PENDING: 'user-quiz/review/pending',
    USER_QUIZ_REVIEW_DETAILS: 'user-quiz/review/:id',
    USER_QUIZ_REVIEW_APPROVE: 'user-quiz/review/approve/:id',
    USER_QUIZ_REVIEW_REJECT: 'user-quiz/review/reject/:id',
    USER_QUIZ_REVIEW_AI_TRIGGER: 'user-quiz/review/ai/:id',
    USER_QUIZ_REVIEW_STATS: 'user-quiz/review/stats',

};
