const Routes = {
  LoginStack: 'LoginStack',
  SplashScreen: 'SplashScreen',
  OnboardingScreen: 'OnboardingScreen',
  SignUp: 'SignUp',
  Login: 'Login',
  ForgotPassword: 'ForgotPassword',
  Verification: 'Verification',
  SetNewPassword: 'SetNewPassword',
  BasicDetails: 'BasicDetails',
  Home: 'Home',
  Notifications: 'Notifications',
  MyProfile: 'MyProfile',
  MyPlaylist: 'MyPlaylist',
  EditPlayList: 'EditPlayList',
  NewPlayList: 'NewPlayList',
  SavePost: 'SavePost',
  DraftPost: 'DraftPost',
  VerifiedPost: 'VerifiedPost',
  PendingPost: 'PendingPost',
  DeclinedPost: 'DeclinedPost',
  CreatePost: 'CreatePost',
  InnerCircleRequest: 'InnerCircleRequest',
  InnerCircle: 'InnerCircle',
  Followers: 'Followers',
  Following: 'Following',
  Likes: 'Likes',
  BlockUsers: 'BlockUsers',
  EditProfile: 'EditProfile',
};

export default Routes;
