const Routes = {
  LoginStack: 'LoginStack',
  SplashScreen: 'SplashScreen',
  OnboardingScreen: 'OnboardingScreen',
  SignUp: 'SignUp',
  Login: 'Login',
  ForgotPassword: 'ForgotPassword',
  Verification: 'Verification',
  SetNewPassword: 'SetNewPassword',
  BasicDetails: 'BasicDetails',
  Home: 'Home',
  Notifications: 'Notifications',
  MyProfile: 'MyProfile',
  MyPlaylist: 'MyPlaylist',
  EditPlayList: 'EditPlayList',
  NewPlayList: 'NewPlayList',
  SavePost: 'SavePost',
  DraftPost: 'DraftPost',
  VerifiedPost: 'VerifiedPost',
  PendingPost: 'PendingPost',
  DeclinedPost: 'DeclinedPost',
  CreatePost: 'CreatePost',
  InnerCircleRequest: 'InnerCircleRequest',
  InnerCircle: 'InnerCircle',
  Followers: 'Followers',
  Following: 'Following',
  Likes: 'Likes',
  BlockUsers: 'BlockUsers',
  EditProfile: 'EditProfile',
  Preferences: 'Preferences',
  EditProfile: 'EditProfile',
  WorkExperience: 'WorkExperience',
  Education: 'Education',
  Certifications: 'Certifications',
  Projects: 'Projects',
  MenuScreen: 'MenuScreen',
  MyProfile: 'MyProfile',
  MyPlaylist: 'MyPlaylist',
  LearningVideo: 'LearningVideo',
  EditPlayList: 'EditPlayList',
  NewPlayList: 'NewPlayList',
  SavePost: 'SavePost',
  DraftPost: 'DraftPost',
  VerifiedPost: 'VerifiedPost',
  PendingPost: 'PendingPost',
  DeclinedPost: 'DeclinedPost',
  CreatePost: 'CreatePost',
  InnerCircleRequest: 'InnerCircleRequest',
  InnerCircle: 'InnerCircle',
  Followers: 'Followers',
  Following: 'Following',
  Likes: 'Likes',
  BlockUsers: 'BlockUsers',
  Settings: 'Settings',
  ChangePassword: 'ChangePassword',
  Search: 'Search',
  OtherProfile: 'OtherProfile',
  HelpScreen: 'HelpScreen',
  Terms: 'Terms',
  UserPost: 'UserPost',
  UserAnalyticsPerf: 'UserAnalyticsPerf',
  Conversation: 'Conversation',
  Chat: 'Chat',
  MyBadge: 'MyBadge',
  Quiz: 'Quiz',
  QuizList: 'QuizList',
  QuizDetails: 'QuizDetails',
  QuizScreen: 'QuizScreen',
  EditGroupProfile: 'EditGroupProfile',
  GroupChat: 'GroupChat',
  GroupProfile: 'GroupProfile',
  groupRequest: 'groupRequest',
  QuizFeedbackScreen: 'QuizFeedbackScreen',
  SupportQueryScreen: 'SupportQueryScreen',
  // User Generated Quiz Routes
  CreateQuiz: 'CreateQuiz',
  EditQuiz: 'EditQuiz',
  CreatorDashboard: 'CreatorDashboard',
  QuizAnalytics: 'QuizAnalytics',
  QuizAccessRequests: 'QuizAccessRequests',
  AIPayment: 'AIPayment',
  MyQuizzes: 'MyQuizzes',
  QuizParticipants: 'QuizParticipants',
  QuizAccessRequests: 'QuizAccessRequests',
  LearningVault: 'LearningVault',
  AreasOfImprovement: 'AreasOfImprovement',    // Main areas page we're building
  TopicInsight: 'TopicInsight',                // Individual topic detailed insight
  LearningAnalytics: 'LearningAnalytics',      // Learning analytics dashboard
  QuizExplanation: 'QuizExplanation',          // Quiz explanation modal/screen
  SetLearningGoal: 'SetLearningGoal',          // Goal setting screen

};

export default Routes;
